version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - ./backend:/app
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "main:app"]

  frontend:
    build:
      context: ./watchly
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./watchly:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: watchly
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
